// countryData.js
const countryData = [
    { name: "United States of America (USA)", code: "US" },
    { name: "Afghanistan (AF)", code: "AF" },
    { name: "Åland Islands (AX)", code: "AX" },
    { name: "Albania (AL)", code: "AL" },
    { name: "Algeria (DZ)", code: "DZ" },
    { name: "Andorra (AD)", code: "AD" },
    { name: "Angola (AO)", code: "AO" },
    { name: "Anguilla (AI)", code: "AI" },
    { name: "Antarctica (AQ)", code: "AQ" },
    { name: "Antigua And Barbuda (AG)", code: "AG" },
    { name: "Argentina (AR)", code: "AR" },
    { name: "Armenia (AM)", code: "AM" },
    { name: "Aruba (AW)", code: "AW" },
    { name: "Australia (AU)", code: "AU" },
    { name: "Austria (AT)", code: "AT" },
    { name: "Azerbaijan (AZ)", code: "AZ" },
    { name: "Bahamas (BS)", code: "BS" },
    { name: "Bahrain (BH)", code: "BH" },
    { name: "Bangladesh (BD)", code: "BD" },
    { name: "Barbados (BB)", code: "BB" },
    { name: "Belarus (BY)", code: "BY" },
    { name: "Belgium (BE)", code: "BE" },
    { name: "Belize (BZ)", code: "BZ" },
    { name: "Benin (BJ)", code: "BJ" },
    { name: "Bermuda (BM)", code: "BM" },
    { name: "Bhutan (BT)", code: "BT" },
    { name: "Bolivia (Plurinational State of) (BO)", code: "BO" },
    { name: "Bonaire, Sint Eustatius And Saba (BQ)", code: "BQ" },
    { name: "Bosnia And Herzegovina (BA)", code: "BA" },
    { name: "Botswana (BW)", code: "BW" },
    { name: "Bouvet Island (BV)", code: "BV" },
    { name: "Brazil (BR)", code: "BR" },
    { name: "British Indian Ocean Territory (IO)", code: "IO" },
    { name: "Brunei Darussalam (BN)", code: "BN" },
    { name: "Bulgaria (BG)", code: "BG" },
    { name: "Burkina Faso (BF)", code: "BF" },
    { name: "Burundi (BI)", code: "BI" },
    { name: "Cambodia (KH)", code: "KH" },
    { name: "Cameroon (CM)", code: "CM" },
    { name: "Canada (CA)", code: "CA" },
    { name: "Cape Verde (CV)", code: "CV" },
    { name: "Cayman Islands (KY)", code: "KY" },
    { name: "Central African Republic (CF)", code: "CF" },
    { name: "Chad (TD)", code: "TD" },
    { name: "Chile (CL)", code: "CL" },
    { name: "China (CN)", code: "CN" },
    { name: "Christmas Island (CX)", code: "CX" },
    { name: "Cocos (Keeling) Islands (CC)", code: "CC" },
    { name: "Colombia (CO)", code: "CO" },
    { name: "Comoros (KM)", code: "KM" },
    { name: "Congo (CG)", code: "CG" },
    { name: "Congo, The Democratic Republic Of The (CD)", code: "CD" },
    { name: "Cook Islands (CK)", code: "CK" },
    { name: "Costa Rica (CR)", code: "CR" },
    { name: "Côte D'ivoire (CI)", code: "CI" },
    { name: "Croatia (HR)", code: "HR" },
    { name: "Cuba (CU)", code: "CU" },
    { name: "Curaçao (CW)", code: "CW" },
    { name: "Cyprus (CY)", code: "CY" },
    { name: "Czech Republic (CZ)", code: "CZ" },
    { name: "Denmark (DK)", code: "DK" },
    { name: "Djibouti (DJ)", code: "DJ" },
    { name: "Dominica (DM)", code: "DM" },
    { name: "Dominican Republic (DO)", code: "DO" },
    { name: "Ecuador (EC)", code: "EC" },
    { name: "Egypt (EG)", code: "EG" },
    { name: "El Salvador (SV)", code: "SV" },
    { name: "Equatorial Guinea (GQ)", code: "GQ" },
    { name: "Eritrea (ER)", code: "ER" },
    { name: "Estonia (EE)", code: "EE" },
    { name: "Ethiopia (ET)", code: "ET" },
    { name: "Falkland Islands (Malvinas) (FK)", code: "FK" },
    { name: "Faroe Islands (FO)", code: "FO" },
    { name: "Fiji (FJ)", code: "FJ" },
    { name: "Finland (FI)", code: "FI" },
    { name: "France (FR)", code: "FR" },
    { name: "French Guiana (GF)", code: "GF" },
    { name: "French Polynesia (PF)", code: "PF" },
    { name: "French Southern Territories (TF)", code: "TF" },
    { name: "Gabon (GA)", code: "GA" },
    { name: "Gambia (GM)", code: "GM" },
    { name: "Georgia (GE)", code: "GE" },
    { name: "Germany (DE)", code: "DE" },
    { name: "Ghana (GH)", code: "GH" },
    { name: "Gibraltar (GI)", code: "GI" },
    { name: "Greece (GR)", code: "GR" },
    { name: "Greenland (GL)", code: "GL" },
    { name: "Grenada (GD)", code: "GD" },
    { name: "Guadeloupe (GP)", code: "GP" },
    { name: "Guatemala (GT)", code: "GT" },
    { name: "Guernsey (GG)", code: "GG" },
    { name: "Guinea (GN)", code: "GN" },
    { name: "Guinea-Bissau (GW)", code: "GW" },
    { name: "Guyana (GY)", code: "GY" },
    { name: "Haiti (HT)", code: "HT" },
    { name: "Heard Island And Mcdonald Islands (HM)", code: "HM" },
    { name: "Holy See (VA)", code: "VA" },
    { name: "Honduras (HN)", code: "HN" },
    { name: "Hong Kong (HK)", code: "HK" },
    { name: "Hungary (HU)", code: "HU" },
    { name: "Iceland (IS)", code: "IS" },
    { name: "India (IN)", code: "IN" },
    { name: "Indonesia (ID)", code: "ID" },
    { name: "Iran, Islamic Republic Of (IR)", code: "IR" },
    { name: "Iraq (IQ)", code: "IQ" },
    { name: "Ireland (IE)", code: "IE" },
    { name: "Isle Of Man (IM)", code: "IM" },
    { name: "Israel (IL)", code: "IL" },
    { name: "Italy (IT)", code: "IT" },
    { name: "Jamaica (JM)", code: "JM" },
    { name: "Japan (JP)", code: "JP" },
    { name: "Jersey (JE)", code: "JE" },
    { name: "Jordan (JO)", code: "JO" },
    { name: "Kazakhstan (KZ)", code: "KZ" },
    { name: "Kenya (KE)", code: "KE" },
    { name: "Kiribati (KI)", code: "KI" },
    { name: "Korea, Democratic People's Republic Of (KP)", code: "KP" },
    { name: "Korea, Republic Of (KR)", code: "KR" },
    { name: "Kuwait (KW)", code: "KW" },
    { name: "Kyrgyzstan (KG)", code: "KG" },
    { name: "Lao People's Democratic Republic (LA)", code: "LA" },
    { name: "Latvia (LV)", code: "LV" },
    { name: "Lebanon (LB)", code: "LB" },
    { name: "Lesotho (LS)", code: "LS" },
    { name: "Liberia (LR)", code: "LR" },
    { name: "Libya (LY)", code: "LY" },
    { name: "Liechtenstein (LI)", code: "LI" },
    { name: "Lithuania (LT)", code: "LT" },
    { name: "Luxembourg (LU)", code: "LU" },
    { name: "Macao (MO)", code: "MO" },
    { name: "Macedonia, The Former Yugoslav Republic Of (MK)", code: "MK" },
    { name: "Madagascar (MG)", code: "MG" },
    { name: "Malawi (MW)", code: "MW" },
    { name: "Malaysia (MY)", code: "MY" },
    { name: "Maldives (MV)", code: "MV" },
    { name: "Mali (ML)", code: "ML" },
    { name: "Malta (MT)", code: "MT" },
    { name: "Marshall Islands (MH)", code: "MH" },
    { name: "Martinique (MQ)", code: "MQ" },
    { name: "Mauritania (MR)", code: "MR" },
    { name: "Mauritius (MU)", code: "MU" },
    { name: "Mayotte (YT)", code: "YT" },
    { name: "Mexico (MX)", code: "MX" },
    { name: "Micronesia, Federated States Of (FM)", code: "FM" },
    { name: "Moldova, Republic Of (MD)", code: "MD" },
    { name: "Monaco (MC)", code: "MC" },
    { name: "Mongolia (MN)", code: "MN" },
    { name: "Montenegro (ME)", code: "ME" },
    { name: "Montserrat (MS)", code: "MS" },
    { name: "Morocco (MA)", code: "MA" },
    { name: "Mozambique (MZ)", code: "MZ" },
    { name: "Myanmar (MM)", code: "MM" },
    { name: "Namibia (NA)", code: "NA" },
    { name: "Nauru (NR)", code: "NR" },
    { name: "Nepal (NP)", code: "NP" },
    { name: "Netherlands (NL)", code: "NL" },
    { name: "New Caledonia (NC)", code: "NC" },
    { name: "New Zealand (NZ)", code: "NZ" },
    { name: "Nicaragua (NI)", code: "NI" },
    { name: "Niger (NE)", code: "NE" },
    { name: "Nigeria (NG)", code: "NG" },
    { name: "Niue (NU)", code: "NU" },
    { name: "Norfolk Island (NF)", code: "NF" },
    { name: "Northern Mariana Islands (MP)", code: "MP" },
    { name: "Norway (NO)", code: "NO" },
    { name: "Oman (OM)", code: "OM" },
    { name: "Pakistan (PK)", code: "PK" },
    { name: "Palau (PW)", code: "PW" },
    { name: "Palestine, State Of (PS)", code: "PS" },
    { name: "Panama (PA)", code: "PA" },
    { name: "Papua New Guinea (PG)", code: "PG" },
    { name: "Paraguay (PY)", code: "PY" },
    { name: "Peru (PE)", code: "PE" },
    { name: "Philippines (PH)", code: "PH" },
    { name: "Pitcairn (PN)", code: "PN" },
    { name: "Poland (PL)", code: "PL" },
    { name: "Portugal (PT)", code: "PT" },
    { name: "Puerto Rico (PR)", code: "PR" },
    { name: "Qatar (QA)", code: "QA" },
    { name: "Réunion (RE)", code: "RE" },
    { name: "Romania (RO)", code: "RO" },
    { name: "Russian Federation (RU)", code: "RU" },
    { name: "Rwanda (RW)", code: "RW" },
    { name: "Saint Barthélemy (BL)", code: "BL" },
    { name: "Saint Helena, Ascension And Tristan Da Cunha (SH)", code: "SH" },
    { name: "Saint Kitts And Nevis (KN)", code: "KN" },
    { name: "Saint Lucia (LC)", code: "LC" },
    { name: "Saint Martin (French Part) (MF)", code: "MF" },
    { name: "Saint Pierre And Miquelon (PM)", code: "PM" },
    { name: "Saint Vincent And The Grenadines (VC)", code: "VC" },
    { name: "Samoa (WS)", code: "WS" },
    { name: "San Marino (SM)", code: "SM" },
    { name: "Sao Tome And Principe (ST)", code: "ST" },
    { name: "Saudi Arabia (SA)", code: "SA" },
    { name: "Senegal (SN)", code: "SN" },
    { name: "Serbia (RS)", code: "RS" },
    { name: "Seychelles (SC)", code: "SC" },
    { name: "Sierra Leone (SL)", code: "SL" },
    { name: "Singapore (SG)", code: "SG" },
    { name: "Sint Maarten (Dutch Part) (SX)", code: "SX" },
    { name: "Slovakia (SK)", code: "SK" },
    { name: "Slovenia (SI)", code: "SI" },
    { name: "Solomon Islands (SB)", code: "SB" },
    { name: "Somalia (SO)", code: "SO" },
    { name: "South Africa (ZA)", code: "ZA" },
    { name: "South Georgia And The South Sandwich Islands (GS)", code: "GS" },
    { name: "South Sudan (SS)", code: "SS" },
    { name: "Spain (ES)", code: "ES" },
    { name: "Sri Lanka (LK)", code: "LK" },
    { name: "Sudan (SD)", code: "SD" },
    { name: "Suriname (SR)", code: "SR" },
    { name: "Svalbard And Jan Mayen (SJ)", code: "SJ" },
    { name: "Swaziland (SZ)", code: "SZ" },
    { name: "Sweden (SE)", code: "SE" },
    { name: "Switzerland (CH)", code: "CH" },
    { name: "Syrian Arab Republic (SY)", code: "SY" },
    { name: "Taiwan (Province Of China) (TW)", code: "TW" },
    { name: "Tajikistan (TJ)", code: "TJ" },
    { name: "Tanzania, United Republic Of (TZ)", code: "TZ" },
    { name: "Thailand (TH)", code: "TH" },
    { name: "Timor-Leste (TL)", code: "TL" },
    { name: "Togo (TG)", code: "TG" },
    { name: "Tokelau (TK)", code: "TK" },
    { name: "Tonga (TO)", code: "TO" },
    { name: "Trinidad And Tobago (TT)", code: "TT" },
    { name: "Tunisia (TN)", code: "TN" },
    { name: "Turkey (TR)", code: "TR" },
    { name: "Turkmenistan (TM)", code: "TM" },
    { name: "Turks And Caicos Islands (TC)", code: "TC" },
    { name: "Tuvalu (TV)", code: "TV" },
    { name: "Uganda (UG)", code: "UG" },
    { name: "Ukraine (UA)", code: "UA" },
    { name: "United Arab Emirates (AE)", code: "AE" },
    { name: "United Kingdom Of Great Britain And Northern Ireland (GB)", code: "GB" },
    { name: "Uruguay (UY)", code: "UY" },
    { name: "Uzbekistan (UZ)", code: "UZ" },
    { name: "Vanuatu (VU)", code: "VU" },
    { name: "Venezuela (Bolivarian Republic Of) (VE)", code: "VE" },
    { name: "Viet Nam (VN)", code: "VN" },
    { name: "Western Sahara (EH)", code: "EH" },
    { name: "Yemen (YE)", code: "YE" },
    { name: "Zambia (ZM)", code: "ZM" },
    { name: "Zimbabwe (ZW)", code: "ZW" },
  ];
  
  
  export default countryData;